/**
 * Media Constants for Yeye Otunba Simisola Ojo Birthday Website
 * This file is auto-generated by a script to list all public images and videos.
 */

export const IMAGES = {
  /** a8b0e582-3e05-4717-ac30-3560e17f94c5.JPG */
  a8b0e582_3e05_4717_ac30_3560e17f94c5: '/images/a8b0e582-3e05-4717-ac30-3560e17f94c5.JPG',
  /** aaa67e80-b83a-4f55-93cb-8fd4bf0728bf.JPG */
  aaa67e80_b83a_4f55_93cb_8fd4bf0728bf: '/images/aaa67e80-b83a-4f55-93cb-8fd4bf0728bf.JPG',
  /** affa7d48-6323-4a6a-a837-161e7bb81460.JPG */
  affa7d48_6323_4a6a_a837_161e7bb81460: '/images/affa7d48-6323-4a6a-a837-161e7bb81460.JPG',
  /** ALH-0d073_34254.JPEG */
  alh_0d073_34254: '/images/ALH-0d073_34254.JPEG',
  /** b307e623-e2ae-4407-a260-ee843a5312db.JPG */
  b307e623_e2ae_4407_a260_ee843a5312db: '/images/b307e623-e2ae-4407-a260-ee843a5312db.JPG',
  /** b5ca7661-d5af-4fbb-be00-59f593984cad.JPG */
  b5ca7661_d5af_4fbb_be00_59f593984cad: '/images/b5ca7661-d5af-4fbb-be00-59f593984cad.JPG',
  /** b7375323-dbb2-41b0-b5d6-7fb5397bf6d0.JPG */
  b7375323_dbb2_41b0_b5d6_7fb5397bf6d0: '/images/b7375323-dbb2-41b0-b5d6-7fb5397bf6d0.JPG',
  /** b848260b-1c89-451c-b07d-46ac336f8d94.JPG */
  b848260b_1c89_451c_b07d_46ac336f8d94: '/images/b848260b-1c89-451c-b07d-46ac336f8d94.JPG',
  /** bae86742-4477-462a-9b78-8e468e76f9fb.JPG */
  bae86742_4477_462a_9b78_8e468e76f9fb: '/images/bae86742-4477-462a-9b78-8e468e76f9fb.JPG',
  /** bcee5a9a-9de7-4fb0-97fd-b2c865c98df2.JPG */
  bcee5a9a_9de7_4fb0_97fd_b2c865c98df2: '/images/bcee5a9a-9de7-4fb0-97fd-b2c865c98df2.JPG',
  /** bee3dc6f-7580-4b88-b033-f5e9803871e0.JPG */
  bee3dc6f_7580_4b88_b033_f5e9803871e0: '/images/bee3dc6f-7580-4b88-b033-f5e9803871e0.JPG',
  /** c58f5382-a289-4a33-87b4-381dbe19da3b.JPG */
  c58f5382_a289_4a33_87b4_381dbe19da3b: '/images/c58f5382-a289-4a33-87b4-381dbe19da3b.JPG',
  /** ccb01568-a9ba-4da5-978b-79f5409cf716.JPG */
  ccb01568_a9ba_4da5_978b_79f5409cf716: '/images/ccb01568-a9ba-4da5-978b-79f5409cf716.JPG',
  /** ceb8bc5e-b6dd-446f-abf7-8f74947d0a03.JPG */
  ceb8bc5e_b6dd_446f_abf7_8f74947d0a03: '/images/ceb8bc5e-b6dd-446f-abf7-8f74947d0a03.JPG',
  /** d6a43af5-1284-4fea-9f97-447fedcb08b6.JPG */
  d6a43af5_1284_4fea_9f97_447fedcb08b6: '/images/d6a43af5-1284-4fea-9f97-447fedcb08b6.JPG',
  /** d8de6f89-5c58-4c40-b38e-83811cb93f40.JPG */
  d8de6f89_5c58_4c40_b38e_83811cb93f40: '/images/d8de6f89-5c58-4c40-b38e-83811cb93f40.JPG',
  /** de1f1630-06ad-4483-af0c-5825f5fd536d.JPG */
  de1f1630_06ad_4483_af0c_5825f5fd536d: '/images/de1f1630-06ad-4483-af0c-5825f5fd536d.JPG',
  /** deeffd0e-a93f-405d-9edf-0cd343546f19.JPG */
  deeffd0e_a93f_405d_9edf_0cd343546f19: '/images/deeffd0e-a93f-405d-9edf-0cd343546f19.JPG',
  /** DSC_0007.JPG */
  dsc_0007: '/images/DSC_0007.JPG',
  /** DSC_0597.JPG */
  dsc_0597: '/images/DSC_0597.JPG',
  /** DSC_7475.JPG */
  dsc_7475: '/images/DSC_7475.JPG',
  /** e095ac33-719c-494e-8eab-595c4e1aa5e9.JPG */
  e095ac33_719c_494e_8eab_595c4e1aa5e9: '/images/e095ac33-719c-494e-8eab-595c4e1aa5e9.JPG',
  /** e44c28a6-99b2-4199-93fa-e45a1b9cf27a.JPG */
  e44c28a6_99b2_4199_93fa_e45a1b9cf27a: '/images/e44c28a6-99b2-4199-93fa-e45a1b9cf27a.JPG',
  /** e8e51c8c-05bf-4467-b856-e00e441848bc.JPG */
  e8e51c8c_05bf_4467_b856_e00e441848bc: '/images/e8e51c8c-05bf-4467-b856-e00e441848bc.JPG',
  /** eef0bc5d-a225-4d58-be6b-9cb53d542d27.JPG */
  eef0bc5d_a225_4d58_be6b_9cb53d542d27: '/images/eef0bc5d-a225-4d58-be6b-9cb53d542d27.JPG',
  /** f59799bc-b335-4177-8099-a50854231f87.JPG */
  f59799bc_b335_4177_8099_a50854231f87: '/images/f59799bc-b335-4177-8099-a50854231f87.JPG',
  /** IMG_0082.JPG */
  img_0082: '/images/IMG_0082.JPG',
  /** IMG_0083.JPG */
  img_0083: '/images/IMG_0083.JPG',
  /** IMG_0084.JPG */
  img_0084: '/images/IMG_0084.JPG',
  /** IMG_0085.JPG */
  img_0085: '/images/IMG_0085.JPG',
  /** IMG_0086.JPG */
  img_0086: '/images/IMG_0086.JPG',
  /** IMG_0131.jpg */
  img_0131: '/images/IMG_0131.jpg',
  /** IMG_0132.jpg */
  img_0132: '/images/IMG_0132.jpg',
  /** IMG_0132(1).jpg */
  img_0132_1: '/images/IMG_0132(1).jpg',
  /** IMG_0288.JPG */
  img_0288: '/images/IMG_0288.JPG',
  /** IMG_0365.jpg */
  img_0365: '/images/IMG_0365.jpg',
  /** IMG_0369.jpg */
  img_0369: '/images/IMG_0369.jpg',
  /** IMG_0431.JPG */
  img_0431: '/images/IMG_0431.JPG',
  /** IMG_0577.JPG */
  img_0577: '/images/IMG_0577.JPG',
  /** 0621F98D-EEA1-4751-BF85-B4A24132B6E8.JPG */
  img_0621f98d_eea1_4751_bf85_b4a24132b6e8: '/images/0621F98D-EEA1-4751-BF85-B4A24132B6E8.JPG',
  /** IMG_0629.jpg */
  img_0629: '/images/IMG_0629.jpg',
  /** IMG_0647.jpg */
  img_0647: '/images/IMG_0647.jpg',
  /** IMG_0667.jpg */
  img_0667: '/images/IMG_0667.jpg',
  /** IMG_0709.jpg */
  img_0709: '/images/IMG_0709.jpg',
  /** 073395c7-124a-4736-95d7-51b2c15616f7.JPG */
  img_073395c7_124a_4736_95d7_51b2c15616f7: '/images/073395c7-124a-4736-95d7-51b2c15616f7.JPG',
  /** IMG_0889.jpg */
  img_0889: '/images/IMG_0889.jpg',
  /** 11c6f185-0eb7-462d-8d25-4a56f672b2f2.JPG */
  img_11c6f185_0eb7_462d_8d25_4a56f672b2f2: '/images/11c6f185-0eb7-462d-8d25-4a56f672b2f2.JPG',
  /** IMG_1286.JPG */
  img_1286: '/images/IMG_1286.JPG',
  /** IMG_1321.jpg */
  img_1321: '/images/IMG_1321.jpg',
  /** IMG_1354.JPG */
  img_1354: '/images/IMG_1354.JPG',
  /** IMG_1355.JPG */
  img_1355: '/images/IMG_1355.JPG',
  /** IMG_1359.JPG */
  img_1359: '/images/IMG_1359.JPG',
  /** IMG_1360.JPG */
  img_1360: '/images/IMG_1360.JPG',
  /** IMG_1528.JPG */
  img_1528: '/images/IMG_1528.JPG',
  /** IMG_1530.JPG */
  img_1530: '/images/IMG_1530.JPG',
  /** IMG_1537.JPG */
  img_1537: '/images/IMG_1537.JPG',
  /** IMG_1538.JPG */
  img_1538: '/images/IMG_1538.JPG',
  /** IMG_1636.JPG */
  img_1636: '/images/IMG_1636.JPG',
  /** IMG_1678.jpg */
  img_1678: '/images/IMG_1678.jpg',
  /** IMG_1726.jpg */
  img_1726: '/images/IMG_1726.jpg',
  /** IMG_1773.JPG */
  img_1773: '/images/IMG_1773.JPG',
  /** IMG_1838.JPG */
  img_1838: '/images/IMG_1838.JPG',
  /** IMG_1886.jpg */
  img_1886: '/images/IMG_1886.jpg',
  /** 19758385-b8c0-4fa3-84f5-21285fde6133.JPG */
  img_19758385_b8c0_4fa3_84f5_21285fde6133: '/images/19758385-b8c0-4fa3-84f5-21285fde6133.JPG',
  /** IMG_1993.jpg */
  img_1993: '/images/IMG_1993.jpg',
  /** 1e056192-911c-4667-9695-5c86c7801189.JPG */
  img_1e056192_911c_4667_9695_5c86c7801189: '/images/1e056192-911c-4667-9695-5c86c7801189.JPG',
  /** IMG_2005.jpg */
  img_2005: '/images/IMG_2005.jpg',
  /** IMG_2052.JPG */
  img_2052: '/images/IMG_2052.JPG',
  /** IMG_2185.jpg */
  img_2185: '/images/IMG_2185.jpg',
  /** IMG_2301.jpg */
  img_2301: '/images/IMG_2301.jpg',
  /** IMG_2408.JPG */
  img_2408: '/images/IMG_2408.JPG',
  /** IMG_2409.JPG */
  img_2409: '/images/IMG_2409.JPG',
  /** IMG_2412.JPG */
  img_2412: '/images/IMG_2412.JPG',
  /** IMG_2413.JPG */
  img_2413: '/images/IMG_2413.JPG',
  /** IMG_2415.JPG */
  img_2415: '/images/IMG_2415.JPG',
  /** IMG_2565.JPG */
  img_2565: '/images/IMG_2565.JPG',
  /** IMG_2628.jpg */
  img_2628: '/images/IMG_2628.jpg',
  /** IMG_2697.jpg */
  img_2697: '/images/IMG_2697.jpg',
  /** IMG_2717.JPG */
  img_2717: '/images/IMG_2717.JPG',
  /** IMG_2745.JPG */
  img_2745: '/images/IMG_2745.JPG',
  /** 274f413a-9d25-40f4-88c9-b3f46f694cd0.JPG */
  img_274f413a_9d25_40f4_88c9_b3f46f694cd0: '/images/274f413a-9d25-40f4-88c9-b3f46f694cd0.JPG',
  /** IMG_2789.jpg */
  img_2789: '/images/IMG_2789.jpg',
  /** IMG_2831.jpg */
  img_2831: '/images/IMG_2831.jpg',
  /** IMG_2916.jpg */
  img_2916: '/images/IMG_2916.jpg',
  /** 2b6a92e8-1cca-46b2-976b-a749d37bfa12.JPG */
  img_2b6a92e8_1cca_46b2_976b_a749d37bfa12: '/images/2b6a92e8-1cca-46b2-976b-a749d37bfa12.JPG',
  /** IMG_3013.jpg */
  img_3013: '/images/IMG_3013.jpg',
  /** IMG_3014.jpg */
  img_3014: '/images/IMG_3014.jpg',
  /** IMG_3104.JPG */
  img_3104: '/images/IMG_3104.JPG',
  /** 31c29265-d702-4213-a5fe-04fc3595f555.JPG */
  img_31c29265_d702_4213_a5fe_04fc3595f555: '/images/31c29265-d702-4213-a5fe-04fc3595f555.JPG',
  /** IMG_3325.JPG */
  img_3325: '/images/IMG_3325.JPG',
  /** IMG_3355.JPG */
  img_3355: '/images/IMG_3355.JPG',
  /** IMG_3356.JPG */
  img_3356: '/images/IMG_3356.JPG',
  /** IMG_3360.JPG */
  img_3360: '/images/IMG_3360.JPG',
  /** IMG_3361.JPG */
  img_3361: '/images/IMG_3361.JPG',
  /** IMG_3362.JPG */
  img_3362: '/images/IMG_3362.JPG',
  /** IMG_3364.JPG */
  img_3364: '/images/IMG_3364.JPG',
  /** IMG_3366.JPG */
  img_3366: '/images/IMG_3366.JPG',
  /** IMG_3367.JPG */
  img_3367: '/images/IMG_3367.JPG',
  /** IMG_3368.JPG */
  img_3368: '/images/IMG_3368.JPG',
  /** IMG_3369.JPG */
  img_3369: '/images/IMG_3369.JPG',
  /** IMG_3383.JPG */
  img_3383: '/images/IMG_3383.JPG',
  /** 341a6e01-6287-45ba-98fa-28d0717fcb04.JPG */
  img_341a6e01_6287_45ba_98fa_28d0717fcb04: '/images/341a6e01-6287-45ba-98fa-28d0717fcb04.JPG',
  /** 3491eade-06ec-494d-8096-b4d919cdf5e8.JPG */
  img_3491eade_06ec_494d_8096_b4d919cdf5e8: '/images/3491eade-06ec-494d-8096-b4d919cdf5e8.JPG',
  /** IMG_3522.jpg */
  img_3522: '/images/IMG_3522.jpg',
  /** IMG_3552.jpg */
  img_3552: '/images/IMG_3552.jpg',
  /** IMG_3561.jpg */
  img_3561: '/images/IMG_3561.jpg',
  /** IMG_3629.jpg */
  img_3629: '/images/IMG_3629.jpg',
  /** IMG_3641.jpg */
  img_3641: '/images/IMG_3641.jpg',
  /** IMG_3722.jpg */
  img_3722: '/images/IMG_3722.jpg',
  /** IMG_3788.jpg */
  img_3788: '/images/IMG_3788.jpg',
  /** IMG_4032.jpg */
  img_4032: '/images/IMG_4032.jpg',
  /** IMG_4200.jpg */
  img_4200: '/images/IMG_4200.jpg',
  /** IMG_4289.JPG */
  img_4289: '/images/IMG_4289.JPG',
  /** 436123be-c7ea-4711-b207-fd9fbd27d017.JPG */
  img_436123be_c7ea_4711_b207_fd9fbd27d017: '/images/436123be-c7ea-4711-b207-fd9fbd27d017.JPG',
  /** IMG_4490.jpg */
  img_4490: '/images/IMG_4490.jpg',
  /** IMG_4687.jpg */
  img_4687: '/images/IMG_4687.jpg',
  /** IMG_4812.jpg */
  img_4812: '/images/IMG_4812.jpg',
  /** IMG_4823.JPG */
  img_4823: '/images/IMG_4823.JPG',
  /** 4862a14e-64e9-410a-a04c-eb12ebf70dee.JPG */
  img_4862a14e_64e9_410a_a04c_eb12ebf70dee: '/images/4862a14e-64e9-410a-a04c-eb12ebf70dee.JPG',
  /** 48cba38f-95ff-41b1-b0e4-70aaf53d6cdf.JPG */
  img_48cba38f_95ff_41b1_b0e4_70aaf53d6cdf: '/images/48cba38f-95ff-41b1-b0e4-70aaf53d6cdf.JPG',
  /** 4e8e95b3-480e-4d0e-8a36-89c052500447.JPG */
  img_4e8e95b3_480e_4d0e_8a36_89c052500447: '/images/4e8e95b3-480e-4d0e-8a36-89c052500447.JPG',
  /** IMG_5136.jpg */
  img_5136: '/images/IMG_5136.jpg',
  /** IMG_5204.jpg */
  img_5204: '/images/IMG_5204.jpg',
  /** IMG_5283.JPG */
  img_5283: '/images/IMG_5283.JPG',
  /** IMG_5286.JPG */
  img_5286: '/images/IMG_5286.JPG',
  /** IMG_5424.JPG */
  img_5424: '/images/IMG_5424.JPG',
  /** IMG_5433.jpg */
  img_5433: '/images/IMG_5433.jpg',
  /** IMG_5440.jpg */
  img_5440: '/images/IMG_5440.jpg',
  /** IMG_5488.JPG */
  img_5488: '/images/IMG_5488.JPG',
  /** IMG_5499.jpg */
  img_5499: '/images/IMG_5499.jpg',
  /** IMG_5573.jpg */
  img_5573: '/images/IMG_5573.jpg',
  /** IMG_5586.jpg */
  img_5586: '/images/IMG_5586.jpg',
  /** IMG_5743.JPG */
  img_5743: '/images/IMG_5743.JPG',
  /** IMG_5748.JPG */
  img_5748: '/images/IMG_5748.JPG',
  /** IMG_5779.JPG */
  img_5779: '/images/IMG_5779.JPG',
  /** IMG_5823.JPG */
  img_5823: '/images/IMG_5823.JPG',
  /** IMG_5836.JPG */
  img_5836: '/images/IMG_5836.JPG',
  /** 5c1a26ec-3bd4-4ac2-b666-08cc4d08ab4f.JPG */
  img_5c1a26ec_3bd4_4ac2_b666_08cc4d08ab4f: '/images/5c1a26ec-3bd4-4ac2-b666-08cc4d08ab4f.JPG',
  /** 5dec321e-bce4-4874-9049-7b7a833fd853.JPG */
  img_5dec321e_bce4_4874_9049_7b7a833fd853: '/images/5dec321e-bce4-4874-9049-7b7a833fd853.JPG',
  /** IMG_6156.jpg */
  img_6156: '/images/IMG_6156.jpg',
  /** IMG_6357.JPG */
  img_6357: '/images/IMG_6357.JPG',
  /** IMG_6358.JPG */
  img_6358: '/images/IMG_6358.JPG',
  /** IMG_6359.JPG */
  img_6359: '/images/IMG_6359.JPG',
  /** IMG_6360.JPG */
  img_6360: '/images/IMG_6360.JPG',
  /** IMG_6362.JPG */
  img_6362: '/images/IMG_6362.JPG',
  /** IMG_6364.JPG */
  img_6364: '/images/IMG_6364.JPG',
  /** IMG_6380.JPG */
  img_6380: '/images/IMG_6380.JPG',
  /** IMG_6648.jpg */
  img_6648: '/images/IMG_6648.jpg',
  /** IMG_6658.JPG */
  img_6658: '/images/IMG_6658.JPG',
  /** 671682c8-66d7-46ec-9170-260f98fcd338.JPG */
  img_671682c8_66d7_46ec_9170_260f98fcd338: '/images/671682c8-66d7-46ec-9170-260f98fcd338.JPG',
  /** IMG_6722.JPG */
  img_6722: '/images/IMG_6722.JPG',
  /** IMG_6859.JPG */
  img_6859: '/images/IMG_6859.JPG',
  /** IMG_6947.JPG */
  img_6947: '/images/IMG_6947.JPG',
  /** 6d525860-92f5-4535-b5d2-3b28fe788736.JPG */
  img_6d525860_92f5_4535_b5d2_3b28fe788736: '/images/6d525860-92f5-4535-b5d2-3b28fe788736.JPG',
  /** IMG_7116.jpg */
  img_7116: '/images/IMG_7116.jpg',
  /** 71825fdb-0a49-4be3-87fe-db39c1954510.JPG */
  img_71825fdb_0a49_4be3_87fe_db39c1954510: '/images/71825fdb-0a49-4be3-87fe-db39c1954510.JPG',
  /** IMG_7192.JPG */
  img_7192: '/images/IMG_7192.JPG',
  /** IMG_7343.JPG */
  img_7343: '/images/IMG_7343.JPG',
  /** IMG_7412.jpg */
  img_7412: '/images/IMG_7412.jpg',
  /** 747f1038-0a1f-4013-8f48-75a5e2fc70be.JPG */
  img_747f1038_0a1f_4013_8f48_75a5e2fc70be: '/images/747f1038-0a1f-4013-8f48-75a5e2fc70be.JPG',
  /** 74ff991e-d6dc-4b3b-84f8-284078853961.JPG */
  img_74ff991e_d6dc_4b3b_84f8_284078853961: '/images/74ff991e-d6dc-4b3b-84f8-284078853961.JPG',
  /** IMG_7886.JPG */
  img_7886: '/images/IMG_7886.JPG',
  /** IMG_7942.JPG */
  img_7942: '/images/IMG_7942.JPG',
  /** IMG_8010.JPG */
  img_8010: '/images/IMG_8010.JPG',
  /** IMG_8096.JPG */
  img_8096: '/images/IMG_8096.JPG',
  /** 82c165a8-5e60-4428-9a1a-3707be0ee2b6.JPG */
  img_82c165a8_5e60_4428_9a1a_3707be0ee2b6: '/images/82c165a8-5e60-4428-9a1a-3707be0ee2b6.JPG',
  /** IMG_8446.JPG */
  img_8446: '/images/IMG_8446.JPG',
  /** IMG_8600.jpg */
  img_8600: '/images/IMG_8600.jpg',
  /** 86237908-b6cd-4a24-ae8d-6e6be518be16.JPG */
  img_86237908_b6cd_4a24_ae8d_6e6be518be16: '/images/86237908-b6cd-4a24-ae8d-6e6be518be16.JPG',
  /** IMG_8636.JPG */
  img_8636: '/images/IMG_8636.JPG',
  /** IMG_8637.JPG */
  img_8637: '/images/IMG_8637.JPG',
  /** IMG_8711.JPG */
  img_8711: '/images/IMG_8711.JPG',
  /** IMG_8717.jpg */
  img_8717: '/images/IMG_8717.jpg',
  /** IMG_8978.jpg */
  img_8978: '/images/IMG_8978.jpg',
  /** 8a5d81fc-637e-40f6-9553-ed6825427892.JPG */
  img_8a5d81fc_637e_40f6_9553_ed6825427892: '/images/8a5d81fc-637e-40f6-9553-ed6825427892.JPG',
  /** 8dc0479a-c6dc-44ce-8967-32f1353c4051.JPG */
  img_8dc0479a_c6dc_44ce_8967_32f1353c4051: '/images/8dc0479a-c6dc-44ce-8967-32f1353c4051.JPG',
  /** 8f77a3e9-9470-4118-8ced-724702bf5c89.JPG */
  img_8f77a3e9_9470_4118_8ced_724702bf5c89: '/images/8f77a3e9-9470-4118-8ced-724702bf5c89.JPG',
  /** IMG_9029.JPG */
  img_9029: '/images/IMG_9029.JPG',
  /** 9151b7d2-c6ba-46b4-a6de-ddedcd5e27bd.JPG */
  img_9151b7d2_c6ba_46b4_a6de_ddedcd5e27bd: '/images/9151b7d2-c6ba-46b4-a6de-ddedcd5e27bd.JPG',
  /** IMG_9269.jpg */
  img_9269: '/images/IMG_9269.jpg',
  /** IMG_9332.JPG */
  img_9332: '/images/IMG_9332.JPG',
  /** IMG_9334.JPG */
  img_9334: '/images/IMG_9334.JPG',
  /** IMG_9367.jpg */
  img_9367: '/images/IMG_9367.jpg',
  /** IMG_9391.JPG */
  img_9391: '/images/IMG_9391.JPG',
  /** 94800000-7b74-4b5c-a04e-eea0ef3cf570.JPG */
  img_94800000_7b74_4b5c_a04e_eea0ef3cf570: '/images/94800000-7b74-4b5c-a04e-eea0ef3cf570.JPG',
  /** IMG_9546.jpg */
  img_9546: '/images/IMG_9546.jpg',
  /** IMG_9841.PNG */
  img_9841: '/images/IMG_9841.PNG',
  /** 9c92c583-42dc-4f1c-ab4b-fcc397ddb254.JPG */
  img_9c92c583_42dc_4f1c_ab4b_fcc397ddb254: '/images/9c92c583-42dc-4f1c-ab4b-fcc397ddb254.JPG',
  /** b5ca7661-d5af-4fbb-be00-59f593984cad.JPG */
  img_b5ca7661_d5af_4fbb_be00_59f593984cad: '/images/b5ca7661-d5af-4fbb-be00-59f593984cad.JPG',
} as const;

export type ImageKey = keyof typeof IMAGES;

export const IMAGES_LIST = Object.values(IMAGES);

export const VIDEOS = {
  /** a61de45b-1ec2-4423-b4f9-a5e61e3ee812.MP4 */
  a61de45b_1ec2_4423_b4f9_a5e61e3ee812: '/videos/a61de45b-1ec2-4423-b4f9-a5e61e3ee812.MP4',
  /** a895a7c1-3e6d-46ec-824e-70dd3ca6de5f.MP4 */
  a895a7c1_3e6d_46ec_824e_70dd3ca6de5f: '/videos/a895a7c1-3e6d-46ec-824e-70dd3ca6de5f.MP4',
  /** ab886b340c9f988dd3ab280f6fc1ddaf.MP4 */
  ab886b340c9f988dd3ab280f6fc1ddaf: '/videos/ab886b340c9f988dd3ab280f6fc1ddaf.MP4',
  /** df5a074e-f7cb-494f-977a-649737f472cc.MP4 */
  df5a074e_f7cb_494f_977a_649737f472cc: '/videos/df5a074e-f7cb-494f-977a-649737f472cc.MP4',
  /** eac6eb8c-77b0-4abc-9f67-b140ca37be1d.MP4 */
  eac6eb8c_77b0_4abc_9f67_b140ca37be1d: '/videos/eac6eb8c-77b0-4abc-9f67-b140ca37be1d.MP4',
  /** IMG_0087.MP4 */
  img_0087: '/videos/IMG_0087.MP4',
  /** IMG_2256.MOV */
  img_2256: '/videos/IMG_2256.MOV',
  /** IMG_7232.MP4 */
  img_7232: '/videos/IMG_7232.MP4',
  /** IMG_7755.MP4 */
  img_7755: '/videos/IMG_7755.MP4',
  /** 307d1867-91f7-4c2f-a40b-85058c7db26a.MP4 */
  vid_307d1867_91f7_4c2f_a40b_85058c7db26a: '/videos/307d1867-91f7-4c2f-a40b-85058c7db26a.MP4',
  /** 54127a52-8376-40ce-8f5c-3c477034c091.MP4 */
  vid_54127a52_8376_40ce_8f5c_3c477034c091: '/videos/54127a52-8376-40ce-8f5c-3c477034c091.MP4',
  /** 689e807d-fed2-4766-be97-97a266c806cc.MP4 */
  vid_689e807d_fed2_4766_be97_97a266c806cc: '/videos/689e807d-fed2-4766-be97-97a266c806cc.MP4',
  /** 7f9dc0f0-b1a3-4060-ac5a-9a1f848ef8e5.MP4 */
  vid_7f9dc0f0_b1a3_4060_ac5a_9a1f848ef8e5: '/videos/7f9dc0f0-b1a3-4060-ac5a-9a1f848ef8e5.MP4',
  /** 942bc9b2-55fa-4851-bc43-309f3ace0d8e.MP4 */
  vid_942bc9b2_55fa_4851_bc43_309f3ace0d8e: '/videos/942bc9b2-55fa-4851-bc43-309f3ace0d8e.MP4',
  /** VIDEO-2026-06-02-20-24-29.mp4 */
  video_2026_06_02_20_24_29: '/videos/VIDEO-2026-06-02-20-24-29.mp4',
} as const;

export type VideoKey = keyof typeof VIDEOS;

export const VIDEOS_LIST = Object.values(VIDEOS);
